update RDB$RELATION_FIELDS set
RDB$FIELD_SOURCE = 'INT_ISZERO'
where (RDB$FIELD_NAME = 'ID_SCHET') and
(RDB$RELATION_NAME = 'PROVODKI');

CREATE DOMAIN DAT_NN AS 
TIMESTAMP
NOT NULL ;

update RDB$RELATION_FIELDS set
RDB$FIELD_SOURCE = 'DAT_NN'
where (RDB$FIELD_NAME = 'DAT') and
(RDB$RELATION_NAME = 'PROVODKI');

update RDB$RELATION_FIELDS set
RDB$FIELD_SOURCE = 'PK'
where (RDB$FIELD_NAME = 'ID_SCHET') and
(RDB$RELATION_NAME = 'PROVODKI')


alter table PROVODKI
add constraint PK_PROVODKI
primary key (DAT,ID_SCHET,ID_PROV);
