
INSERT INTO CLASS_ATTRIBUTES
(OID, ATTRIBUTE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE, CLASSID)
VALUES (-106, 2, 'Номер прав', 1, -106);

INSERT INTO CLASS_ATTRIBUTES
(OID, ATTRIBUTE_ID, ATTRIBUTE_NAME, ATTRIBUTE_TYPE, CLASSID)
VALUES (-106, 3, 'Вид перевозок', 1, -106);
