SET TERM ^ ;



CREATE OR ALTER TRIGGER OPLNAKL_GENID FOR OPLNAKL
ACTIVE BEFORE INSERT POSITION 5
AS

begin
  if (new.id is null) then begin
    new.id = gen_id(OPLNAKL_GEN, 1);
  end
end
^


SET TERM ; ^





SET TERM ^ ;



CREATE OR ALTER TRIGGER OPLNAKL_PROVODKI_BD10 FOR OPLNAKL
ACTIVE BEFORE DELETE POSITION 10
AS
  declare variable oidTransh integer;
begin
  delete from provodki p
    where p.id_nakl=old.id and
      p.tip=8294 /*'“»œ “–¿Õÿ»'*/ ;
end
^


SET TERM ; ^


/* Privileges of triggers */
GRANT UPDATE, REFERENCES ON OPLNAKL TO TRIGGER OPLNAKL_PROVODKI_BD10;
GRANT SELECT, DELETE ON PROVODKI TO TRIGGER OPLNAKL_PROVODKI_BD10;
GRANT EXECUTE ON PROCEDURE GET_OID_OBJECTS_PC TO TRIGGER OPLNAKL_PROVODKI_BD10;
