/******************************************************************************/
/***               Generated by IBExpert 04.06.2012 12:04:04                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;


CREATE TRIGGER TOVAR_ALL_VW_AU0 FOR TOVAR_ALL_VW
ACTIVE AFTER UPDATE POSITION 0
AS
BEGIN
  POST_EVENT 'DUMMY_EVENT';
END
^


ALTER TRIGGER TOVAR_ALL_VW_AU0
AS
  declare variable classid integer;
  declare variable count_dependent_tovar integer;
begin
  select oid
    from GET_OID_OBJECTS_PC('ТИП ТОВАРЫ',-100)
    into :classid;
  if (new.id <> new.id_analog) then begin
    select z(count(*))
    from tovar t
    where t.id_analog=new.id
      and t.delmarked=0
    into :count_dependent_tovar;
    if (count_dependent_tovar>0) then begin
      execute procedure error ('У товара есть зависимые. Он должен быть главным аналогом');
    end
  end
  update objects o
    set
      o.name=substr(new.name,1,50),
      o.delmarked=new.delmarked,
      o.oid=new.id,
      o.fullname=new.fullname
    where
      o.oid=old.id and o.classid=:classid;
 
  update tovar t
    set t.ediz = new.ediz,
      t.cena=new.cena,
      t.cenavx=new.cenavx,
      t.kod1=new.kod1,
      t.kod2=new.kod2,
      t.kod3=new.kod3,
      t.tara=new.tara,
      t.name=new.name,
      t.delmarked=new.delmarked,
      t.skladskaya=new.skladskaya,
      t.id_analog=new.id_analog,
      t.oid=new.id,
      t.weight=new.weight,
      t.gruppa1=upper(new.gruppa1),
      t.gruppa2=new.gruppa2,
      t.gruppa3=new.gruppa3,
      t.gruppa4=new.gruppa4,
      t.COPPERPERKM=new.copperperkm,
      t.kodved=new.kodved
    where
      t.oid=old.id;

end
^


SET TERM ; ^


