SET TERM ^ ;

CREATE OR ALTER PROCEDURE VOZVRAT_POST_DELMARK_PC(
    OID INTEGER)
AS
  DECLARE VARIABLE TIP INTEGER;
begin
  select oid
    from GET_OID_OBJECTS_PC('¬Œ«¬–¿“ œŒ—“¿¬Ÿ» ”',-100)
    into :tip;
  execute procedure possible_to_delmark(:oid,:tip, 1);
  update naklo om
    set om.delmarked=1
    where om.id_nakl=:oid and
      om.tip=:tip and
      om.delmarked=0;
end^

SET TERM ; ^

GRANT EXECUTE ON PROCEDURE GET_OID_OBJECTS_PC TO PROCEDURE VOZVRAT_POST_DELMARK_PC;

GRANT EXECUTE ON PROCEDURE POSSIBLE_TO_DELMARK TO PROCEDURE VOZVRAT_POST_DELMARK_PC;

GRANT SELECT,UPDATE ON NAKLO TO PROCEDURE VOZVRAT_POST_DELMARK_PC;

GRANT EXECUTE ON PROCEDURE VOZVRAT_POST_DELMARK_PC TO SYSDBA;
GRANT EXECUTE ON PROCEDURE VOZVRAT_POST_DELMARK_PC TO BUXG;
GRANT EXECUTE ON PROCEDURE VOZVRAT_POST_DELMARK_PC TO SNAB;
GRANT EXECUTE ON PROCEDURE VOZVRAT_POST_DELMARK_PC TO POWER_USER;

