INSERT INTO OBJECTS (OID, CLASSID, DELMARKED, NAME, FULLNAME, PREDEFINED, ISDEFAULT)
VALUES (-17, 13167, 0, 'ПРИХОДНАЯ НАЛОГОВАЯ УТОЧНЁННАЯ', 'Полученная налоговая (уточн)', '1', NULL);

INSERT INTO OBJECTS (OID, CLASSID, DELMARKED, NAME, FULLNAME, PREDEFINED, ISDEFAULT)
VALUES (-16, 13167, 0, 'ТОВАРНЫЙ КАССОВЫЙ ЧЕК', 'Товарный чек', '1', NULL);

INSERT INTO OBJECTS (OID, CLASSID, DELMARKED, NAME, FULLNAME, PREDEFINED, ISDEFAULT)
VALUES (-15, 13167, 0, 'ТРАНСПОРТНЫЙ БИЛЕТ', 'Транспорный билет', '1', NULL);

INSERT INTO OBJECTS (OID, CLASSID, DELMARKED, NAME, FULLNAME, PREDEFINED, ISDEFAULT)
VALUES (-14, 13167, 0, 'СЧЕТ ЗА УСЛУГИ СВЯЗИ', 'Счёт за услуги связи', '1', NULL);

INSERT INTO OBJECTS (OID, CLASSID, DELMARKED, NAME, FULLNAME, PREDEFINED, ISDEFAULT)
VALUES (-13, 13167, 0, 'СЧЕТ ЗА УСЛУГИ ПО СЧЕТЧИКАМ', 'Счёт за услуги по счётчикам', '1', NULL);

INSERT INTO OBJECTS (OID, CLASSID, DELMARKED, NAME, FULLNAME, PREDEFINED, ISDEFAULT)
VALUES (-12, 13167, 0, 'ЗАЯВКА ПЛАТЕЛЬЩИКА', 'Заявка плательщика', '1', NULL);

INSERT INTO OBJECTS (OID, CLASSID, DELMARKED, NAME, FULLNAME, PREDEFINED, ISDEFAULT)
VALUES (-11, 3001, 0, 'ПП', 'ПП', '1', NULL);

INSERT INTO OBJECTS (OID, CLASSID, DELMARKED, NAME, FULLNAME, PREDEFINED, ISDEFAULT)
VALUES (-10, 3001, 0, 'ЗЦ', 'ЗЦ', '1', NULL);

INSERT INTO OBJECTS (OID, CLASSID, DELMARKED, NAME, FULLNAME, PREDEFINED, ISDEFAULT)
VALUES (-9, 3001, 0, 'НАЛОГОВАЯ УТОЧНЯЮЩАЯ', 'Налоговая (уточн)', '1', NULL);


