SET TERM ^ ;

CREATE OR ALTER PROCEDURE NAKLRF_UNPOST_PC(
    ID_NAKL INTEGER)
AS
begin
  execute procedure naklr_unpost_common_pc(:id_nakl,
    'РАСХОДНЫЕ НАКЛАДНЫЕ НА ФИНУСЛУГИ',
    'Нельзя вернуть не расходную накладную на услуги');
end^

SET TERM ; ^

GRANT EXECUTE ON PROCEDURE NAKLR_UNPOST_COMMON_PC TO PROCEDURE NAKLRF_UNPOST_PC;

GRANT EXECUTE ON PROCEDURE NAKLRF_UNPOST_PC TO SYSDBA;
GRANT EXECUTE ON PROCEDURE NAKLRF_UNPOST_PC TO BOSSES;
GRANT EXECUTE ON PROCEDURE NAKLRF_UNPOST_PC TO BUXG;
GRANT EXECUTE ON PROCEDURE NAKLRF_UNPOST_PC TO MANAGER;
GRANT EXECUTE ON PROCEDURE NAKLRF_UNPOST_PC TO POWER_USER;
