/******************************************************************************/
/***               Generated by IBExpert 28.08.2014 19:51:15                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ;


CREATE TRIGGER NAKLO_AUDIT_BU80 FOR NAKLO
ACTIVE BEFORE UPDATE POSITION 80
AS
/*DECLARE VARIABLE ID_MANAGER_USER INTEGER;*/
DECLARE VARIABLE HAS_ROLE SMALLINT;
DECLARE VARIABLE HAS_MANAGER SMALLINT;
DECLARE VARIABLE classid integer;
DECLARE VARIABLE name varchar(50);
DECLARE VARIABLE fk1 integer;
declare variable data_fields_change smallint;
declare variable naklp_modified integer;

BEGIN
/*$$IBEC$$     if ((old.posted<>0)  ) then begin
      if (new.delmarked<>0) then begin
        execute procedure error ('Запрещено удалять проведенный документ');
      end
    end
    if ((old.blocked<>0)  ) then begin
      if (new.delmarked<>0) then begin
        execute procedure error ('Запрещено удалять блокированный документ');
      end
    end
    if (old.delmarked<>0) then begin
      if ((new.posted<>0)) then begin
        execute procedure error ('Запрещено проводить удалённый документ');
      end
    end
    if (old.delmarked<>0) then begin
      if ((new.blocked<>0)) then begin
        execute procedure error ('Запрещено блокировать удалённый документ');
      end
    end $$IBEC$$*/

/*$$IBEC$$   fk1=0;
  if (trim(new.comment)<>trim(old.comment)) then begin
    fk1=1;
  end $$IBEC$$*/
  execute procedure can_modifytable2_pc('naklo',new.id_nakl,2,:fk1,0);

 /*склад*/
 if (new.tip in (1,2,5,6,103,30,-110)) then begin
   if (new.tip not in (1,-110)) then begin
     if ((z(new.id_nakl)<>z(old.id_nakl)) or (trim(new.id)<>trim(old.id)) or
      (z(new.kurs)<>z(old.kurs)) or (z(new.nds)<>z(old.nds)) or
      (z(new.id_izg)<>z(old.id_izg)) or (z(new.id_zak)<>z(old.id_zak)) or
      (z(new.id_manager)<>z(old.id_manager)) or (z(new.nalog_nds)<>z(old.nalog_nds)) or
      (z(new.id_currency)<>z(old.id_currency)) or (z(new.id_sklad)<>z(old.id_sklad)) or
      (trim(new.comment)<>trim(old.comment)) or (z(new.parent_id_nakl)<>z(old.parent_id_nakl)) or
      (ExtractDate(new.dat)<>ExtractDate(old.dat))) then begin
       data_fields_change=1;
     end else begin
       data_fields_change=0;
     end
    end /*   if (new.tip not in (1))*/

    if (old.posted<>0 and data_fields_change<>0) then begin
      execute procedure error ('Запрещено менять проведенный документ');
    end
    select has_role from get_roles_pc('SKLAD') into :has_role;
    if(1 <> :has_role) then begin
  
      select has_role from get_roles_pc('MANAGER') into :has_role;
      if(1 = :has_role) then begin
       /*выясняем текущего менеджера*/
        select has_manager from has_idmanager_pc(old.id_manager) into :has_manager;
        if (has_manager=0) then begin
          execute procedure error('Запрещено переоформлять отгрузки на другого менеджера');
        end
      end /*manager*/
    end
  
    if (new.blocked<>old.blocked) then begin
      if (user<>'SYSDBA') then begin
        select has_role from get_roles_pc('sklad') into :has_role;
        if (1<>:has_role) then begin
          execute procedure error('Запрещено менять блокировку');
        end
      end
    end
  
    if (new.blocked=1 or new.posted<>0) then begin
      if (new.dat<>old.dat) then begin
        execute procedure error('Запрещено менять дату у заблокированных отгрузок');
      end
      if (new.tip<>old.tip) then begin
        execute procedure error('Запрещено менять тип отгрузки у заблокированных отгрузок');
      end
      if (trim(new.comment)<>trim(old.comment)) then begin
        select has_role from get_roles_pc('sklad') into :has_role;
        if(1 <> :has_role) then begin
          execute procedure error('Запрещено менять комментарий у заблокированных отгрузок');
        end
      end
    end /*(new.blocked=1 or new.posted=1) */
    if (new.posted<>0) then begin 
      if (new.parent_id_nakl<>old.parent_id_nakl) then begin
        if (old.tip = 1) then begin
          execute procedure error('Запрещено менять № родительской накладной у проведённого прихода');
        end
        if (old.tip = -110) then begin
          execute procedure error('Запрещено менять № родительской накладной у проведённого возврата');
        end else begin
          execute procedure error('Запрещено менять № расходной накладной у проведённой отгрузки');
        end
      end
    end /*(new.posted<>0)*/
  end /*склад*/
  
END
^


SET TERM ; ^


