SET TERM ^ ;

CREATE PROCEDURE NAKLO_UNDELETE_PC(
    ID_NAKL INTEGER)
AS
begin
  update naklo
  set delmarked=0
  where delmarked=1 and id_nakl=:id_nakl;
end^

SET TERM ; ^

GRANT SELECT,UPDATE ON NAKLO TO PROCEDURE NAKLO_UNDELETE_PC;

GRANT EXECUTE ON PROCEDURE NAKLO_UNDELETE_PC TO "PUBLIC";
GRANT EXECUTE ON PROCEDURE NAKLO_UNDELETE_PC TO SYSDBA;
