/******************************************************************************/
/***               Generated by IBExpert 03.01.2015 13:31:07                ***/
/******************************************************************************/



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR OID_GEN;

CREATE TABLE EDIZ (
    OID       PK /* PK = INTEGER NOT NULL */,
    NAME      FIRM_NAME /* FIRM_NAME = VARCHAR(50) */,
    KOD       INT_NULL /* INT_NULL = INTEGER */,
    FULLNAME  VAR100_N /* VAR100_N = VARCHAR(100) */
);




/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: EDIZ_BI0 */
CREATE OR ALTER TRIGGER EDIZ_BI0 FOR EDIZ
ACTIVE BEFORE INSERT POSITION 0
AS
begin
  if (new.oid is null) then begin
    new.oid = gen_id(oid_gen,1);
  end
end
^


SET TERM ; ^



/* Fields descriptions */

DESCRIBE FIELD OID TABLE EDIZ
'Идентификатор единицы измерения';

DESCRIBE FIELD NAME TABLE EDIZ
'Название сокращённое. 
Начальное значение из справочника товаров.
Например "км"';

DESCRIBE FIELD KOD TABLE EDIZ
'Код единицы измерения. Для xml налоговой накладной';

DESCRIBE FIELD FULLNAME TABLE EDIZ
'Длинное название. Например "километр"';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/



ALTER TABLE EDIZ
ADD DELMARKED S_0
